# fly.toml app configuration file generated for pine-script-wrapper on 2026-01-21T01:41:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pine-script-wrapper'
primary_region = 'iad'

[build]

[env]
  USE_WARM_BROWSER = 'true'
  CHROME_CACHE_DIR = '/data/screenshots/chrome-cache'
  KEEP_ALIVE_ENABLED = 'true'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = 'screenshots'
  destination = '/data/screenshots'

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096
